AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Serverless web application for uploading files to S3
Resources:
  uploaderThanhct:
    Type: AWS::Serverless::Function
    Properties:
      Description: Serverless web application for uploading files to S3
      Handler: uploader.handler
      Runtime: nodejs8.10
      CodeUri: build/package.zip
      MemorySize: 128
      Policies:
        - S3CrudPolicy:
            BucketName:
              Ref: destBucket
      Timeout: 60
      Events:
        root:
          Type: Api
          Properties:
            Path: /
            Method: get
        getProxy:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: get
        postProxy:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: post
      Environment:
        Variables:
          DEST_BUCKET:
            Ref: destBucket
Parameters:
  destBucket:
    Type: String
    Description: Name of the S3 Bucket to put uploaded files into (must exist prior to deployment)
